export const CLOUD_LOGIN = 'https://cloud.appveen.com/api/a/rbac/login';
export const CLOUD_CHECK = 'https://cloud.appveen.com/api/a/rbac/check';
export const REDIS = 'redis://127.0.0.1:9996';
export const CLOUD_LOGIN_KEY = 'CLOUD_LOGIN_KEY';
export const MY_DEFECTS = 'https://cloud.appveen.com/api/c/XCRO/defects';
export const MY_STORIES = 'https://cloud.appveen.com/api/c/XCRO/storyTask';
export const GO_BACK = { name: 'Go Back', value: 'GO_BACK' };
export const EXIT = { name: 'Exit', value: 'EXIT' };
export const DEFECT_DETAILS = 'https://cloud.appveen.com/api/c/XCRO/defects';
